import React, {
  useState,
  useRef,
  useCallback,
  useEffect,
  useMemo,
} from "react";
import { T } from "./lib/tokens.js";
import {
  MODES,
  PLATFORMS,
  DETAILS,
  DEFAULT_VARIATION_CONFIG,
} from "./lib/constants.js";
import { fetchWithRetry, getTokenLimitParam } from "./lib/api.js";
import { buildSystem, buildUser, parseResult } from "./lib/prompts.js";
import { Icons } from "./components/Icons.jsx";
import { NeuralMesh } from "./components/NeuralMesh.jsx";
import {
  Glass,
  SectionLabel,
  CopyBtn,
  Collapsible,
} from "./components/UI.jsx";
import { SubjectInput } from "./components/SubjectInput.jsx";
import { VariationControls } from "./components/VariationControls.jsx";
import { HistoryPanel } from "./components/HistoryPanel.jsx";
import { AnalysisProgress } from "./components/AnalysisProgress.jsx";

export default function App() {
  const [images, setImages] = useState([]);
  const [mode, setMode] = useState("single");
  const [platform, setPlatform] = useState("universal");
  const [detail, setDetail] = useState("standard");
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState(null);
  const [dragOver, setDragOver] = useState(false);
  const [history, setHistory] = useState([]);
  const [styleSubject, setStyleSubject] = useState("");
  const [variationConfig, setVariationConfig] = useState(
    DEFAULT_VARIATION_CONFIG,
  );

  const fileRef = useRef(null);
  const resultsRef = useRef(null);

  const handleFiles = useCallback((files) => {
    const imageFiles = Array.from(files).filter((f) =>
      f.type.startsWith("image/"),
    );
    if (!imageFiles.length) return;

    const readPromises = imageFiles.map(
      (file) =>
        new Promise((resolve) => {
          const reader = new FileReader();
          reader.onload = (e) => {
            resolve({
              id: Date.now() + Math.random(),
              name: file.name,
              size: file.size,
              src: e.target.result,
              file,
            });
          };
          reader.onerror = () => resolve(null);
          reader.readAsDataURL(file);
        }),
    );

    Promise.all(readPromises).then((results) => {
      const valid = results.filter(Boolean);
      if (valid.length) setImages((prev) => [...prev, ...valid]);
    });
  }, []);

  const handleDrop = useCallback(
    (e) => {
      e.preventDefault();
      setDragOver(false);
      handleFiles(e.dataTransfer.files);
    },
    [handleFiles],
  );

  const removeImage = (id) => {
    setImages((p) => p.filter((i) => i.id !== id));
    if (result) setResult(null);
  };

  useEffect(() => {
    if (result && resultsRef.current) {
      setTimeout(
        () =>
          resultsRef.current?.scrollIntoView({
            behavior: "smooth",
            block: "start",
          }),
        100,
      );
    }
  }, [result]);

  const maxTokens = useMemo(() => {
    if (detail === "concise") return 2048;
    if (detail === "standard") return 4096;
    return 8192;
  }, [detail]);

  const analyze = async () => {
    if (!images.length) return;
    if (mode === "style-transfer" && !styleSubject.trim()) return;
    setAnalyzing(true);
    setResult(null);

    try {
      const apiKey = import.meta.env.VITE_OPENAI_API_KEY || "";
      if (!apiKey) {
        throw new Error(
          "Missing API key. Set VITE_OPENAI_API_KEY in your environment variables.",
        );
      }

      const systemPromptText = buildSystem(
        mode,
        platform,
        detail,
        variationConfig,
        styleSubject,
      );
      const userPromptText = buildUser(
        mode,
        platform,
        detail,
        images.length,
        variationConfig,
        styleSubject,
      );

      const userContent = [
        { type: "text", text: userPromptText },
        ...images.map((img) => ({
          type: "image_url",
          image_url: { url: img.src, detail: "high" },
        })),
      ];

      const model = "gpt-5-mini-2025-08-07";
      const payload = {
        model,
        ...getTokenLimitParam(model, maxTokens),
        messages: [
          { role: "system", content: systemPromptText },
          { role: "user", content: userContent },
        ],
      };

      const data = await fetchWithRetry(
        "https://api.openai.com/v1/chat/completions",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify(payload),
        },
      );

      if (!data?.choices?.length) {
        throw new Error("No response generated by the model.");
      }

      const text = data.choices[0].message.content;
      const parsed = parseResult(text, mode);
      setResult(parsed);

      if (parsed.prompt && !parsed.error) {
        setHistory((prev) => [
          {
            id: Date.now(),
            mode,
            platform,
            detail,
            prompt: parsed.prompt,
            thumbnail: images[0]?.src || null,
            timestamp: new Date().toISOString(),
          },
          ...prev.slice(0, 19),
        ]);
      }
    } catch (err) {
      setResult({ error: true, message: `Analysis failed: ${err.message}` });
    } finally {
      setAnalyzing(false);
    }
  };

  const loadFromHistory = (h) => {
    setMode(h.mode);
    setPlatform(h.platform);
    setDetail(h.detail);
    setResult({
      prompt: h.prompt,
      technical: null,
      tags: [],
      negativePrompt: null,
      variants: [],
    });
  };

  const exportPrompt = () => {
    if (!result?.prompt && (!result?.variants || result.variants.length === 0))
      return;

    const lines = [
      "VASEY/AI REGENESYS Prompt Generator — Export",
      `Mode: ${mode} | Platform: ${platform} | Detail: ${detail}`,
      `Generated: ${new Date().toLocaleString()}`,
      "\u2500".repeat(60),
    ];

    if (result.prompt)
      lines.push(`\nPROMPT:\n${result.prompt}`);
    if (result.technical)
      lines.push(`\nTECHNICAL:\n${result.technical}`);
    if (result.tags?.length)
      lines.push(`\nTAGS:\n${result.tags.join(", ")}`);
    if (result.negativePrompt)
      lines.push(`\nNEGATIVE:\n${result.negativePrompt}`);
    if (result.variants?.length) {
      result.variants.forEach((v, i) => {
        lines.push(`\nVARIANT ${i + 1}:\n${v}`);
      });
    }

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const blobUrl = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = blobUrl;
    a.download = `vai-regen-prompt-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(blobUrl);
  };

  const analyzeLabel =
    mode === "single"
      ? "Analyze Image"
      : mode === "multi"
        ? "Synthesize Hybrid"
        : mode === "negative"
          ? "Generate Negative Prompt"
          : mode === "metadata"
            ? "Assemble Metadata"
            : mode === "style-transfer"
              ? "Extract & Transfer Style"
              : "Generate Variations";

  const canAnalyze =
    images.length > 0 &&
    !analyzing &&
    !(mode === "style-transfer" && !styleSubject.trim());

  return (
    <div
      style={{
        minHeight: "100vh",
        background: `linear-gradient(180deg, ${T.bg} 0%, #0C0D14 50%, ${T.bg} 100%)`,
        color: T.text,
        fontFamily: "'Reddit Sans', sans-serif",
        position: "relative",
        overflowX: "hidden",
      }}
    >
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Reddit+Sans:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
        @keyframes vai-spin { from{transform:rotate(0deg)} to{transform:rotate(360deg)} }
        @keyframes vai-fadeIn { from{opacity:0;transform:translateY(6px)} to{opacity:1;transform:translateY(0)} }
        @keyframes vai-pulseGlow { 0%,100%{box-shadow:0 0 20px rgba(0,206,209,0.15)} 50%{box-shadow:0 0 40px rgba(0,206,209,0.3)} }
        * { box-sizing:border-box; margin:0; padding:0; }
        html { overflow-x: hidden; }
        ::-webkit-scrollbar { width:5px; }
        ::-webkit-scrollbar-track { background:transparent; }
        ::-webkit-scrollbar-thumb { background:rgba(100,116,139,0.15); border-radius:3px; }
        ::-webkit-scrollbar-thumb:hover { background:rgba(100,116,139,0.3); }
        ::selection { background:rgba(0,206,209,0.25); }
        input[type=range]::-webkit-slider-thumb { -webkit-appearance: none; appearance: none; width: 14px; height: 14px; border-radius: 50%; background: ${T.teal}; cursor: pointer; box-shadow: 0 0 8px rgba(0,206,209,0.4); border: 2px solid ${T.bg}; }
        input[type=range]::-moz-range-thumb { width: 14px; height: 14px; border-radius: 50%; background: ${T.teal}; cursor: pointer; box-shadow: 0 0 8px rgba(0,206,209,0.4); border: 2px solid ${T.bg}; }
        textarea::placeholder { color: rgba(100,116,139,0.4); }
      `}</style>

      <NeuralMesh />

      {/* Ambient top gradient */}
      <div
        style={{
          position: "fixed",
          top: 0,
          left: 0,
          right: 0,
          height: 200,
          background:
            "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(0,206,209,0.04) 0%, transparent 70%)",
          zIndex: 1,
          pointerEvents: "none",
        }}
      />

      {/* Header */}
      <header
        style={{
          position: "sticky",
          top: 0,
          zIndex: 20,
          padding: "20px 16px 16px",
          background: "rgba(9,10,15,0.88)",
          backdropFilter: "blur(24px)",
          WebkitBackdropFilter: "blur(24px)",
          borderBottom: `1px solid ${T.borderSubtle}`,
        }}
      >
        <div
          style={{
            maxWidth: 900,
            margin: "0 auto",
            display: "flex",
            alignItems: "flex-start",
            justifyContent: "space-between",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                width: 52,
                height: 52,
                borderRadius: 14,
                background:
                  "linear-gradient(135deg, rgba(0,206,209,0.1), rgba(34,164,193,0.02))",
                border: "1px solid rgba(0,206,209,0.2)",
                boxShadow: "0 0 20px rgba(0,206,209,0.08) inset",
                flexShrink: 0,
              }}
            >
              <Icons.AppIcon size={30} />
            </div>
            <div style={{ minWidth: 0 }}>
              <div
                style={{
                  fontSize: 9,
                  letterSpacing: 3,
                  color: T.dim,
                  fontWeight: 500,
                  textTransform: "uppercase",
                  marginBottom: 2,
                }}
              >
                VASEY/AI PRESENTS
              </div>
              <h1
                style={{
                  fontFamily: "'Bebas Neue', sans-serif",
                  fontSize: 34,
                  letterSpacing: 2,
                  lineHeight: 1,
                  background: `linear-gradient(135deg, ${T.teal} 0%, ${T.beam} 40%, ${T.cyan} 100%)`,
                  WebkitBackgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                  margin: 0,
                }}
              >
                REGENESYS
              </h1>
              <div
                style={{
                  fontFamily: "'Bebas Neue', sans-serif",
                  fontSize: 16,
                  letterSpacing: 1.5,
                  color: T.teal,
                  marginTop: -1,
                }}
              >
                PROMPT GENERATOR
              </div>
            </div>
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 6,
              flexShrink: 0,
              marginTop: 2,
            }}
          >
            <span
              style={{
                fontSize: 9,
                color: T.dim,
                fontFamily: "'JetBrains Mono', monospace",
                padding: "3px 8px",
                background: T.glass,
                borderRadius: 5,
                border: `1px solid ${T.borderSubtle}`,
              }}
            >
              v1.2
            </span>
          </div>
        </div>
      </header>

      {/* Main */}
      <main
        style={{
          position: "relative",
          zIndex: 5,
          maxWidth: 900,
          margin: "0 auto",
          padding: "20px 16px 140px",
        }}
      >
        {/* Analysis Mode */}
        <Glass style={{ padding: 16, marginBottom: 16 }}>
          <SectionLabel>ANALYSIS MODE</SectionLabel>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(2, 1fr)",
              gap: "10px",
              marginTop: "12px",
            }}
          >
            {MODES.map((m) => {
              const on = mode === m.id;
              const Ic = Icons[m.icon] || Icons.Image;
              return (
                <button
                  key={m.id}
                  onClick={() => {
                    setMode(m.id);
                    if (result) setResult(null);
                  }}
                  aria-pressed={on}
                  style={{
                    background: on
                      ? `linear-gradient(135deg, ${T.tealGlass}, rgba(34,164,193,0.06))`
                      : T.glass,
                    border: `1px solid ${on ? T.tealBorderActive : T.border}`,
                    borderRadius: 12,
                    padding: "14px 14px",
                    textAlign: "left",
                    cursor: "pointer",
                    transition: "all 0.2s ease",
                    minWidth: 0,
                    overflow: "hidden",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: 7,
                      marginBottom: 4,
                    }}
                  >
                    <span style={{ color: on ? T.teal : T.slate }}>
                      <Ic />
                    </span>
                    <span
                      style={{
                        fontSize: 13,
                        fontWeight: 600,
                        color: on ? T.text : T.muted,
                        whiteSpace: "nowrap",
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                      }}
                    >
                      {m.label}
                    </span>
                  </div>
                  <div
                    style={{
                      fontSize: 10,
                      color: T.dim,
                      lineHeight: 1.3,
                      whiteSpace: "nowrap",
                      overflow: "hidden",
                      textOverflow: "ellipsis",
                    }}
                  >
                    {m.desc}
                  </div>
                </button>
              );
            })}
          </div>
        </Glass>

        {/* Output Configuration */}
        <Glass accent style={{ padding: 16, marginBottom: 16 }}>
          <SectionLabel>OUTPUT CONFIGURATION</SectionLabel>
          <div style={{ marginTop: 12 }}>
            <div
              style={{
                fontSize: 10,
                color: T.dim,
                letterSpacing: 1,
                textTransform: "uppercase",
                marginBottom: 6,
              }}
            >
              Target Platform
            </div>
            <div
              style={{ display: "flex", flexWrap: "wrap", gap: 5 }}
              role="radiogroup"
              aria-label="Target Platform"
            >
              {PLATFORMS.map((p) => (
                <button
                  key={p.id}
                  onClick={() => setPlatform(p.id)}
                  role="radio"
                  aria-checked={platform === p.id}
                  style={{
                    background:
                      platform === p.id ? T.tealGlass : "transparent",
                    border: `1px solid ${platform === p.id ? T.tealBorder : T.border}`,
                    borderRadius: 7,
                    padding: "5px 10px",
                    fontSize: 11,
                    color: platform === p.id ? T.teal : T.muted,
                    cursor: "pointer",
                    transition: "all 0.2s ease",
                    fontFamily: "'Reddit Sans', sans-serif",
                  }}
                >
                  {p.label}
                </button>
              ))}
            </div>
          </div>
          <div style={{ marginTop: 14 }}>
            <div
              style={{
                fontSize: 10,
                color: T.dim,
                letterSpacing: 1,
                textTransform: "uppercase",
                marginBottom: 6,
              }}
            >
              Detail Level
            </div>
            <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
              {DETAILS.map((d) => (
                <button
                  key={d.id}
                  onClick={() => setDetail(d.id)}
                  aria-pressed={detail === d.id}
                  style={{
                    flex: 1,
                    minWidth: "100px",
                    background:
                      detail === d.id
                        ? `linear-gradient(135deg, ${T.tealGlass}, rgba(34,164,193,0.04))`
                        : "transparent",
                    border: `1px solid ${detail === d.id ? T.tealBorder : T.border}`,
                    borderRadius: 9,
                    padding: "8px 8px",
                    textAlign: "center",
                    cursor: "pointer",
                    transition: "all 0.2s ease",
                  }}
                >
                  <div
                    style={{
                      fontSize: 12,
                      fontWeight: 600,
                      color: detail === d.id ? T.text : T.muted,
                    }}
                  >
                    {d.label}
                  </div>
                  <div style={{ fontSize: 9, color: T.dim, marginTop: 1 }}>
                    {d.desc}
                  </div>
                </button>
              ))}
            </div>
          </div>
        </Glass>

        {mode === "style-transfer" && (
          <SubjectInput value={styleSubject} onChange={setStyleSubject} />
        )}
        {mode === "variation" && (
          <VariationControls
            config={variationConfig}
            onChange={setVariationConfig}
          />
        )}

        {/* Upload Zone */}
        <Glass
          glow={dragOver}
          style={{
            padding: images.length > 0 ? 14 : 32,
            minHeight: images.length > 0 ? "auto" : 180,
            marginBottom: 16,
            display: "flex",
            flexDirection: "column",
            alignItems: images.length > 0 ? "stretch" : "center",
            justifyContent: images.length > 0 ? "flex-start" : "center",
            transition: "all 0.3s ease",
            animation: dragOver ? "vai-pulseGlow 1.5s ease infinite" : "none",
          }}
        >
          <input
            ref={fileRef}
            type="file"
            accept="image/*"
            multiple
            aria-label="Upload images"
            style={{ display: "none" }}
            onChange={(e) => {
              handleFiles(e.target.files);
              e.target.value = "";
            }}
          />

          {images.length === 0 ? (
            <div
              onClick={() => fileRef.current?.click()}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  fileRef.current?.click();
                }
              }}
              onDragOver={(e) => {
                e.preventDefault();
                setDragOver(true);
              }}
              onDragLeave={() => setDragOver(false)}
              onDrop={handleDrop}
              role="button"
              tabIndex={0}
              aria-label="Upload images by clicking or dropping files"
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: 10,
                width: "100%",
                cursor: "pointer",
              }}
            >
              <div
                style={{
                  width: 48,
                  height: 48,
                  borderRadius: 14,
                  background: `linear-gradient(135deg, ${T.tealGlass}, rgba(34,164,193,0.08))`,
                  border: `1px solid ${T.tealBorder}`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: T.teal,
                }}
              >
                <Icons.Upload />
              </div>
              <div style={{ textAlign: "center" }}>
                <div
                  style={{
                    fontSize: 14,
                    fontWeight: 600,
                    color: T.textSoft,
                  }}
                >
                  Drop images or tap to upload
                </div>
                <div style={{ fontSize: 11, color: T.dim, marginTop: 2 }}>
                  PNG, JPG, WebP &middot; Up to 20MB
                </div>
              </div>
            </div>
          ) : (
            <div>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  marginBottom: 10,
                }}
              >
                <span
                  style={{
                    fontFamily: "'Bebas Neue', sans-serif",
                    fontSize: 13,
                    letterSpacing: 1.5,
                    color: T.muted,
                  }}
                >
                  UPLOADED ({images.length})
                </span>
                <div style={{ display: "flex", gap: 6 }}>
                  <button
                    onClick={() => {
                      setImages([]);
                      setResult(null);
                    }}
                    style={{
                      background: "rgba(239,68,68,0.06)",
                      border: "1px solid rgba(239,68,68,0.1)",
                      borderRadius: 7,
                      padding: "3px 10px",
                      fontSize: 10,
                      color: "rgba(239,68,68,0.7)",
                      cursor: "pointer",
                      fontFamily: "'Reddit Sans', sans-serif",
                    }}
                  >
                    Clear
                  </button>
                  <button
                    onClick={() => fileRef.current?.click()}
                    style={{
                      background: T.glassHover,
                      border: `1px solid ${T.border}`,
                      borderRadius: 7,
                      padding: "3px 10px",
                      fontSize: 10,
                      color: T.muted,
                      cursor: "pointer",
                      fontFamily: "'Reddit Sans', sans-serif",
                    }}
                  >
                    + Add
                  </button>
                </div>
              </div>
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(auto-fill, minmax(80px, 1fr))",
                  gap: 6,
                }}
                onDragOver={(e) => {
                  e.preventDefault();
                  setDragOver(true);
                }}
                onDragLeave={() => setDragOver(false)}
                onDrop={handleDrop}
              >
                {images.map((img) => (
                  <div
                    key={img.id}
                    style={{
                      position: "relative",
                      borderRadius: 8,
                      overflow: "hidden",
                      border: `1px solid ${T.border}`,
                      aspectRatio: "1",
                    }}
                  >
                    <img
                      src={img.src}
                      alt={img.name}
                      style={{
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                      }}
                    />
                    <button
                      onClick={() => removeImage(img.id)}
                      aria-label={`Remove ${img.name}`}
                      style={{
                        position: "absolute",
                        top: 3,
                        right: 3,
                        width: 20,
                        height: 20,
                        borderRadius: 5,
                        background: "rgba(0,0,0,0.65)",
                        border: `1px solid ${T.border}`,
                        color: T.muted,
                        cursor: "pointer",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                      }}
                    >
                      <Icons.X />
                    </button>
                    <div
                      style={{
                        position: "absolute",
                        bottom: 0,
                        left: 0,
                        right: 0,
                        padding: "10px 5px 3px",
                        background:
                          "linear-gradient(transparent, rgba(0,0,0,0.75))",
                        fontSize: 8,
                        color: T.dim,
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                        whiteSpace: "nowrap",
                        fontFamily: "'JetBrains Mono', monospace",
                      }}
                    >
                      {img.name}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </Glass>

        {/* Analyze Button */}
        <button
          onClick={analyze}
          disabled={!canAnalyze}
          aria-busy={analyzing}
          style={{
            width: "100%",
            padding: "13px 20px",
            borderRadius: 11,
            border: "none",
            background: !canAnalyze
              ? T.panel
              : analyzing
                ? T.tealGlass
                : `linear-gradient(135deg, ${T.teal} 0%, ${T.beam} 50%, rgba(34,164,193,0.85) 100%)`,
            color: !canAnalyze ? T.dim : T.text,
            fontSize: 13,
            fontWeight: 600,
            fontFamily: "'Reddit Sans', sans-serif",
            letterSpacing: 0.3,
            cursor: !canAnalyze ? "not-allowed" : "pointer",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: 8,
            transition: "all 0.3s ease",
            boxShadow:
              canAnalyze && !analyzing
                ? `0 4px 20px ${T.tealGlow}, 0 1px 0 inset rgba(255,255,255,0.1)`
                : "none",
            marginBottom: 20,
          }}
        >
          {analyzing ? (
            <>
              <Icons.Loader /> Deconstructing Visual DNA...
            </>
          ) : (
            <>
              <Icons.Sparkle /> {analyzeLabel}
            </>
          )}
        </button>

        {analyzing && <AnalysisProgress stage={analyzing} />}

        <HistoryPanel
          history={history}
          onSelect={loadFromHistory}
          onClear={() => setHistory([])}
          onRemove={(id) => setHistory((h) => h.filter((x) => x.id !== id))}
        />

        {/* Results */}
        {result && (
          <div
            ref={resultsRef}
            style={{
              display: "flex",
              flexDirection: "column",
              gap: 14,
              animation: "vai-fadeIn 0.4s ease",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                margin: "4px 0",
              }}
            >
              <span
                style={{
                  flex: 1,
                  height: 1,
                  background: `linear-gradient(90deg, transparent, ${T.tealBorder}, transparent)`,
                }}
              />
              <span
                style={{
                  fontSize: 9,
                  letterSpacing: 2.5,
                  color: T.teal,
                  fontFamily: "'Bebas Neue', sans-serif",
                  padding: "3px 12px",
                  borderRadius: 20,
                  background: T.tealGlass,
                  border: `1px solid ${T.tealBorder}`,
                }}
              >
                RESULTS
              </span>
              <span
                style={{
                  flex: 1,
                  height: 1,
                  background: `linear-gradient(90deg, transparent, ${T.tealBorder}, transparent)`,
                }}
              />
            </div>

            {result.error ? (
              <Glass style={{ padding: 20 }}>
                <div
                  role="alert"
                  style={{ color: T.error, fontSize: 13, lineHeight: 1.6 }}
                >
                  {result.message}
                </div>
                <div style={{ fontSize: 11, color: T.dim, marginTop: 8 }}>
                  An issue occurred. If the error persists, try a smaller image
                  or fewer images.
                </div>
              </Glass>
            ) : (
              <>
                <div style={{ display: "flex", justifyContent: "flex-end" }}>
                  <button
                    onClick={exportPrompt}
                    style={{
                      background: T.glassHover,
                      border: `1px solid ${T.border}`,
                      borderRadius: 7,
                      padding: "5px 12px",
                      fontSize: 11,
                      color: T.muted,
                      cursor: "pointer",
                      display: "flex",
                      alignItems: "center",
                      gap: 5,
                      fontFamily: "'Reddit Sans', sans-serif",
                      transition: "all 0.2s ease",
                    }}
                  >
                    <Icons.Download /> Export .txt
                  </button>
                </div>

                {result.prompt && (
                  <Glass
                    glow
                    style={{
                      padding: 16,
                      position: "relative",
                      overflow: "hidden",
                    }}
                  >
                    <div
                      style={{
                        position: "absolute",
                        top: 0,
                        left: 0,
                        right: 0,
                        height: 1,
                        background: `linear-gradient(90deg, transparent 0%, ${T.teal} 50%, transparent 100%)`,
                        opacity: 0.3,
                      }}
                    />
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        marginBottom: 10,
                      }}
                    >
                      <span
                        style={{
                          fontFamily: "'Bebas Neue', sans-serif",
                          fontSize: 15,
                          letterSpacing: 1.5,
                          color: T.teal,
                        }}
                      >
                        {mode === "negative"
                          ? "NEGATIVE PROMPT"
                          : "GENERATED PROMPT"}
                      </span>
                      <CopyBtn text={result.prompt} />
                    </div>
                    <div
                      style={{
                        background:
                          "linear-gradient(135deg, rgba(9,10,15,0.6), rgba(14,16,23,0.8))",
                        borderRadius: 9,
                        padding: 14,
                        border: `1px solid ${T.borderSubtle}`,
                        fontSize: 12,
                        lineHeight: 1.75,
                        color: T.textSoft,
                        fontFamily: "'JetBrains Mono', monospace",
                        whiteSpace: "pre-wrap",
                        maxHeight: 400,
                        overflowY: "auto",
                        wordBreak: "break-word",
                      }}
                    >
                      {result.prompt}
                    </div>
                    {platform !== "universal" && (
                      <div
                        style={{
                          marginTop: 6,
                          fontSize: 9,
                          color: T.dim,
                          fontFamily: "'JetBrains Mono', monospace",
                        }}
                      >
                        Optimized for{" "}
                        {PLATFORMS.find((p) => p.id === platform)?.label}
                      </div>
                    )}
                  </Glass>
                )}

                {result.variants?.length > 0 && (
                  <Glass accent style={{ padding: 16 }}>
                    <Collapsible title="PROMPT VARIANTS">
                      <div
                        style={{
                          display: "flex",
                          flexDirection: "column",
                          gap: 10,
                        }}
                      >
                        {result.variants.map((v, i) => (
                          <div key={i} style={{ position: "relative" }}>
                            <div
                              style={{
                                display: "flex",
                                alignItems: "center",
                                justifyContent: "space-between",
                                marginBottom: 6,
                              }}
                            >
                              <span
                                style={{
                                  fontSize: 10,
                                  color: T.teal,
                                  fontFamily: "'JetBrains Mono', monospace",
                                  fontWeight: 600,
                                }}
                              >
                                VARIANT {i + 1}
                              </span>
                              <CopyBtn text={v} />
                            </div>
                            <div
                              style={{
                                background: "rgba(9,10,15,0.5)",
                                borderRadius: 8,
                                padding: 12,
                                border: `1px solid ${T.borderSubtle}`,
                                fontSize: 11,
                                lineHeight: 1.65,
                                color: "rgba(241,245,249,0.75)",
                                fontFamily: "'JetBrains Mono', monospace",
                                whiteSpace: "pre-wrap",
                                wordBreak: "break-word",
                              }}
                            >
                              {v}
                            </div>
                          </div>
                        ))}
                      </div>
                    </Collapsible>
                  </Glass>
                )}

                {result.technical && (
                  <Glass accent style={{ padding: 16 }}>
                    <Collapsible title="TECHNICAL BREAKDOWN">
                      <div
                        style={{
                          display: "flex",
                          justifyContent: "flex-end",
                          marginBottom: 8,
                        }}
                      >
                        <CopyBtn text={result.technical} />
                      </div>
                      <div
                        style={{
                          fontSize: 12,
                          lineHeight: 1.7,
                          color: "rgba(241,245,249,0.7)",
                          whiteSpace: "pre-wrap",
                          wordBreak: "break-word",
                        }}
                      >
                        {result.technical}
                      </div>
                    </Collapsible>
                  </Glass>
                )}

                {result.tags?.length > 0 && (
                  <Glass style={{ padding: 16 }}>
                    <Collapsible title="STYLE TAGS">
                      <div
                        style={{
                          display: "flex",
                          justifyContent: "flex-end",
                          marginBottom: 8,
                        }}
                      >
                        <CopyBtn text={result.tags.join(", ")} />
                      </div>
                      <div
                        style={{ display: "flex", flexWrap: "wrap", gap: 5 }}
                      >
                        {result.tags.map((tag, i) => (
                          <span
                            key={i}
                            style={{
                              background: `linear-gradient(135deg, ${T.tealGlass}, rgba(51,65,85,0.08))`,
                              border: "1px solid rgba(0,206,209,0.12)",
                              borderRadius: 6,
                              padding: "3px 9px",
                              fontSize: 10,
                              color: T.cyan,
                              fontFamily: "'JetBrains Mono', monospace",
                            }}
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    </Collapsible>
                  </Glass>
                )}

                {result.negativePrompt && mode !== "negative" && (
                  <Glass style={{ padding: 16 }}>
                    <Collapsible
                      title="NEGATIVE PROMPT"
                      defaultOpen={false}
                    >
                      <div
                        style={{
                          display: "flex",
                          justifyContent: "flex-end",
                          marginBottom: 8,
                        }}
                      >
                        <CopyBtn text={result.negativePrompt} />
                      </div>
                      <div
                        style={{
                          background: "rgba(239,68,68,0.04)",
                          borderRadius: 9,
                          padding: 12,
                          border: "1px solid rgba(239,68,68,0.08)",
                          fontSize: 11,
                          lineHeight: 1.6,
                          color: "rgba(241,245,249,0.6)",
                          fontFamily: "'JetBrains Mono', monospace",
                          whiteSpace: "pre-wrap",
                          wordBreak: "break-word",
                        }}
                      >
                        {result.negativePrompt}
                      </div>
                    </Collapsible>
                  </Glass>
                )}
              </>
            )}
          </div>
        )}
      </main>

      {/* Footer */}
      <footer
        style={{
          position: "fixed",
          bottom: 0,
          left: 0,
          right: 0,
          zIndex: 20,
          padding: "14px 20px 18px",
          background: "rgba(9,10,15,0.95)",
          backdropFilter: "blur(16px)",
          WebkitBackdropFilter: "blur(16px)",
          borderTop: `1px solid ${T.borderSubtle}`,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          gap: 10,
          fontFamily: "'JetBrains Mono', monospace",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: 4,
            textAlign: "center",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 8,
              fontSize: 10,
            }}
          >
            <span style={{ color: T.textSoft, fontWeight: 600 }}>
              &copy; {new Date().getFullYear()} VASEY/AI
            </span>
            <span style={{ color: T.borderSubtle }}>|</span>
            <span style={{ color: T.dim }}>
              REGENESYS Prompt Generator v1.2
            </span>
          </div>
          <div
            style={{
              fontSize: 9,
              opacity: 0.6,
              lineHeight: 1.4,
              color: T.dim,
            }}
          >
            A VASEY/AI creation. Part of the Vasey Multimedia content series.
            <span style={{ margin: "0 6px", color: T.borderSubtle }}>
              &bull;
            </span>
            All rights reserved.
          </div>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <Icons.VaseyLogo size={24} style={{ opacity: 0.8 }} />
          <span
            style={{ height: 12, width: 1, background: T.borderSubtle }}
          />
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 6,
              fontSize: 9,
              color: T.dim,
            }}
          >
            <span
              style={{
                width: 5,
                height: 5,
                borderRadius: "50%",
                background: T.teal,
                boxShadow: `0 0 6px ${T.teal}`,
              }}
            />
            <span>Systems Online</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
