import React, {
  useState,
  useRef,
  useCallback,
  useEffect,
  useMemo,
} from "react";
import { T } from "./lib/tokens.js";
import {
  MODES,
  PLATFORMS,
  DETAILS,
  DEFAULT_VARIATION_CONFIG,
} from "./lib/constants.js";
import { fetchWithRetry, getTokenLimitParam } from "./lib/api.js";
import { buildSystem, buildUser, parseResult } from "./lib/prompts.js";
import { Icons } from "./components/Icons.jsx";
import { NeuralMesh } from "./components/NeuralMesh.jsx";
import {
  Glass,
  SectionLabel,
  CopyBtn,
  Collapsible,
} from "./components/UI.jsx";
import { SubjectInput } from "./components/SubjectInput.jsx";
import { VariationControls } from "./components/VariationControls.jsx";
import { HistoryPanel } from "./components/HistoryPanel.jsx";
import { AnalysisProgress } from "./components/AnalysisProgress.jsx";

export default function App() {
  const [images, setImages] = useState([]);
  const [mode, setMode] = useState("single");
  const [platform, setPlatform] = useState("universal");
  const [detail, setDetail] = useState("standard");
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState(null);
  const [dragOver, setDragOver] = useState(false);
  const [history, setHistory] = useState([]);
  const [styleSubject, setStyleSubject] = useState("");
  const [variationConfig, setVariationConfig] = useState(
    DEFAULT_VARIATION_CONFIG,
  );

  const fileRef = useRef(null);
  const resultsRef = useRef(null);

  const handleFiles = useCallback((files) => {
    const imageFiles = Array.from(files).filter((f) =>
      f.type.startsWith("image/"),
    );
    if (!imageFiles.length) return;

    const readPromises = imageFiles.map(
      (file) =>
        new Promise((resolve) => {
          const reader = new FileReader();
          reader.onload = (e) => {
            resolve({
              id: Date.now() + Math.random(),
              name: file.name,
              size: file.size,
              src: e.target.result,
              file,
            });
          };
          reader.onerror = () => resolve(null);
          reader.readAsDataURL(file);
        }),
    );

    Promise.all(readPromises).then((results) => {
      const valid = results.filter(Boolean);
      if (valid.length) setImages((prev) => [...prev, ...valid]);
    });
  }, []);

  const handleDrop = useCallback(
    (e) => {
      e.preventDefault();
      setDragOver(false);
      handleFiles(e.dataTransfer.files);
    },
    [handleFiles],
  );

  const removeImage = (id) => {
    setImages((p) => p.filter((i) => i.id !== id));
    if (result) setResult(null);
  };

  useEffect(() => {
    if (result && resultsRef.current) {
      setTimeout(
        () =>
          resultsRef.current?.scrollIntoView({
            behavior: "smooth",
            block: "start",
          }),
        100,
      );
    }
  }, [result]);

  const maxTokens = useMemo(() => {
    if (detail === "concise") return 2048;
    if (detail === "standard") return 4096;
    return 8192;
  }, [detail]);

  const analyze = async () => {
    if (!images.length) return;
    if (mode === "style-transfer" && !styleSubject.trim()) return;
    setAnalyzing(true);
    setResult(null);

    try {
      const apiKey = import.meta.env.VITE_OPENAI_API_KEY || "";
      if (!apiKey) {
        throw new Error(
          "Missing API key. Set VITE_OPENAI_API_KEY in your environment variables.",
        );
      }

      const systemPromptText = buildSystem(
        mode,
        platform,
        detail,
        variationConfig,
        styleSubject,
      );
      const userPromptText = buildUser(
        mode,
        platform,
        detail,
        images.length,
        variationConfig,
        styleSubject,
      );

      const userContent = [
        { type: "text", text: userPromptText },
        ...images.map((img) => ({
          type: "image_url",
          image_url: { url: img.src, detail: "high" },
        })),
      ];

      const model = "gpt-5-mini-2025-08-07";
      const payload = {
        model,
        ...getTokenLimitParam(model, maxTokens),
        messages: [
          { role: "system", content: systemPromptText },
          { role: "user", content: userContent },
        ],
      };

      const data = await fetchWithRetry(
        "https://api.openai.com/v1/chat/completions",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify(payload),
        },
      );

      if (!data?.choices?.length) {
        throw new Error("No response generated by the model.");
      }

      const text = data.choices[0].message.content;
      const parsed = parseResult(text, mode);
      setResult(parsed);

      if (parsed.prompt && !parsed.error) {
        setHistory((prev) => [
          {
            id: Date.now(),
            mode,
            platform,
            detail,
            prompt: parsed.prompt,
            thumbnail: images[0]?.src || null,
            timestamp: new Date().toISOString(),
          },
          ...prev.slice(0, 19),
        ]);
      }
    } catch (err) {
      setResult({ error: true, message: `Analysis failed: ${err.message}` });
    } finally {
      setAnalyzing(false);
    }
  };

  const loadFromHistory = (h) => {
    setMode(h.mode);
    setPlatform(h.platform);
    setDetail(h.detail);
    setResult({
      prompt: h.prompt,
      technical: null,
      tags: [],
      negativePrompt: null,
      variants: [],
    });
  };

  const exportPrompt = () => {
    if (!result?.prompt && (!result?.variants || result.variants.length === 0))
      return;

    const lines = [
      "VASEY/AI REGENESYS Prompt Generator — Export",
      `Mode: ${mode} | Platform: ${platform} | Detail: ${detail}`,
      `Generated: ${new Date().toLocaleString()}`,
      "\u2500".repeat(60),
    ];

    if (result.prompt)
      lines.push(`\nPROMPT:\n${result.prompt}`);
    if (result.technical)
      lines.push(`\nTECHNICAL:\n${result.technical}`);
    if (result.tags?.length)
      lines.push(`\nTAGS:\n${result.tags.join(", ")}`);
    if (result.negativePrompt)
      lines.push(`\nNEGATIVE:\n${result.negativePrompt}`);
    if (result.variants?.length) {
      result.variants.forEach((v, i) => {
        lines.push(`\nVARIANT ${i + 1}:\n${v}`);
      });
    }

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const blobUrl = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = blobUrl;
    a.download = `vai-regen-prompt-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(blobUrl);
  };

  const analyzeLabel =
    mode === "single"
      ? "Analyze Image"
      : mode === "multi"
        ? "Synthesize Hybrid"
        : mode === "negative"
          ? "Generate Negative Prompt"
          : mode === "metadata"
            ? "Assemble Metadata"
            : mode === "style-transfer"
              ? "Extract & Transfer Style"
              : "Generate Variations";

  const canAnalyze =
    images.length > 0 &&
    !analyzing &&
    !(mode === "style-transfer" && !styleSubject.trim());

  return (
    <div
      className="vai-shell"
      style={{
        background: `linear-gradient(180deg, ${T.bg} 0%, #0C0D14 50%, ${T.bg} 100%)`,
        color: T.text,
        fontFamily: "'Reddit Sans', sans-serif",
        position: "relative",
        overflowX: "hidden",
      }}
    >
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Reddit+Sans:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
        @keyframes vai-spin { from{transform:rotate(0deg)} to{transform:rotate(360deg)} }
        @keyframes vai-fadeIn { from{opacity:0;transform:translateY(6px)} to{opacity:1;transform:translateY(0)} }
        @keyframes vai-pulseGlow { 0%,100%{box-shadow:0 0 20px rgba(0,206,209,0.15)} 50%{box-shadow:0 0 40px rgba(0,206,209,0.3)} }
        * { box-sizing:border-box; margin:0; padding:0; }
        html, body { background: ${T.bg}; overflow-x: hidden; }
        .vai-shell { min-height: 100vh; min-height: 100dvh; }
        ::-webkit-scrollbar { width:5px; }
        ::-webkit-scrollbar-track { background:transparent; }
        ::-webkit-scrollbar-thumb { background:rgba(100,116,139,0.15); border-radius:3px; }
        ::-webkit-scrollbar-thumb:hover { background:rgba(100,116,139,0.3); }
        ::selection { background:rgba(0,206,209,0.25); }
        input[type=range]::-webkit-slider-thumb { -webkit-appearance: none; appearance: none; width: 14px; height: 14px; border-radius: 50%; background: ${T.teal}; cursor: pointer; box-shadow: 0 0 8px rgba(0,206,209,0.4); border: 2px solid ${T.bg}; }
        input[type=range]::-moz-range-thumb { width: 14px; height: 14px; border-radius: 50%; background: ${T.teal}; cursor: pointer; box-shadow: 0 0 8px rgba(0,206,209,0.4); border: 2px solid ${T.bg}; }
        textarea::placeholder { color: rgba(100,116,139,0.4); }
      `}</style>

      <NeuralMesh />

      {/* Ambient top gradient */}
      <div
        style={{
          position: "fixed",
          top: 0,
          left: 0,
          right: 0,
          height: 200,
          background:
            "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(0,206,209,0.04) 0%, transparent 70%)",
          zIndex: 1,
          pointerEvents: "none",
        }}
      />

      {/* Header */}
      <header
        style={{
          position: "relative",
          zIndex: 20,
          padding:
            "calc(24px + env(safe-area-inset-top, 0px)) calc(20px + env(safe-area-inset-right, 0px)) 20px calc(20px + env(safe-area-inset-left, 0px))",
          textAlign: "center",
          animation: "vai-fadeIn 0.6s ease",
        }}
      >
        <div
          style={{
            fontSize: 11,
            letterSpacing: "0.25em",
            color: T.dim,
            fontWeight: 500,
            textTransform: "uppercase",
            fontFamily: "'Reddit Sans', sans-serif",
            marginBottom: 16,
          }}
        >
          VASEY/AI PRESENTS
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: 12,
            marginBottom: 8,
          }}
        >
          <Icons.AppIcon size={38} />
          <h1
            style={{
              fontFamily: "'Bebas Neue', sans-serif",
              fontSize: 42,
              letterSpacing: 3,
              lineHeight: 1,
              background: `linear-gradient(135deg, ${T.teal} 0%, ${T.beam} 40%, ${T.cyan} 100%)`,
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              margin: 0,
            }}
          >
            REGENESYS
          </h1>
          <span
            style={{
              fontSize: 10,
              color: T.dim,
              fontFamily: "'JetBrains Mono', monospace",
              padding: "3px 10px",
              background: T.glass,
              borderRadius: 20,
              border: `1px solid ${T.borderSubtle}`,
              whiteSpace: "nowrap",
            }}
          >
            v1.2
          </span>
        </div>
        <div
          style={{
            fontSize: 14,
            color: T.muted,
            fontFamily: "'Reddit Sans', sans-serif",
            fontWeight: 300,
            letterSpacing: 0.5,
          }}
        >
          Visual Prompt Reverse-Engineering &amp; Generation System.
        </div>
      </header>

      {/* Main */}
      <main
        style={{
          position: "relative",
          zIndex: 5,
          maxWidth: 900,
          margin: "0 auto",
          padding:
            "20px calc(16px + env(safe-area-inset-right, 0px)) 40px calc(16px + env(safe-area-inset-left, 0px))",
        }}
      >
        {/* Analysis Mode */}
        <Glass style={{ padding: 16, marginBottom: 16 }}>
          <SectionLabel>ANALYSIS MODE</SectionLabel>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(2, 1fr)",
              gap: "10px",
              marginTop: "12px",
            }}
          >
            {MODES.map((m) => {
              const on = mode === m.id;
              const Ic = Icons[m.icon] || Icons.Image;
              return (
                <button
                  key={m.id}
                  onClick={() => {
                    setMode(m.id);
                    if (result) setResult(null);
                  }}
                  aria-pressed={on}
                  style={{
                    background: on
                      ? `linear-gradient(135deg, ${T.tealGlass}, rgba(34,164,193,0.06))`
                      : T.glass,
                    border: `1px solid ${on ? T.tealBorderActive : T.border}`,
                    borderRadius: 12,
                    padding: "14px 14px",
                    textAlign: "left",
                    cursor: "pointer",
                    transition: "all 0.2s ease",
                    minWidth: 0,
                    overflow: "hidden",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: 7,
                      marginBottom: 4,
                    }}
                  >
                    <span style={{ color: on ? T.teal : T.slate }}>
                      <Ic />
                    </span>
                    <span
                      style={{
                        fontSize: 13,
                        fontWeight: 600,
                        color: on ? T.text : T.muted,
                        whiteSpace: "nowrap",
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                      }}
                    >
                      {m.label}
                    </span>
                  </div>
                  <div
                    style={{
                      fontSize: 10,
                      color: T.dim,
                      lineHeight: 1.3,
                      whiteSpace: "nowrap",
                      overflow: "hidden",
                      textOverflow: "ellipsis",
                    }}
                  >
                    {m.desc}
                  </div>
                </button>
              );
            })}
          </div>
        </Glass>

        {/* Output Configuration */}
        <Glass accent style={{ padding: 16, marginBottom: 16 }}>
          <SectionLabel>OUTPUT CONFIGURATION</SectionLabel>
          <div style={{ marginTop: 12 }}>
            <div
              style={{
                fontSize: 10,
                color: T.dim,
                letterSpacing: 1,
                textTransform: "uppercase",
                marginBottom: 6,
              }}
            >
              Target Platform
            </div>
            <div
              style={{ display: "flex", flexWrap: "wrap", gap: 5 }}
              role="radiogroup"
              aria-label="Target Platform"
            >
              {PLATFORMS.map((p) => (
                <button
                  key={p.id}
                  onClick={() => setPlatform(p.id)}
                  role="radio"
                  aria-checked={platform === p.id}
                  style={{
                    background:
                      platform === p.id ? T.tealGlass : "transparent",
                    border: `1px solid ${platform === p.id ? T.tealBorder : T.border}`,
                    borderRadius: 7,
                    padding: "5px 10px",
                    fontSize: 11,
                    color: platform === p.id ? T.teal : T.muted,
                    cursor: "pointer",
                    transition: "all 0.2s ease",
                    fontFamily: "'Reddit Sans', sans-serif",
                  }}
                >
                  {p.label}
                </button>
              ))}
            </div>
          </div>
          <div style={{ marginTop: 14 }}>
            <div
              style={{
                fontSize: 10,
                color: T.dim,
                letterSpacing: 1,
                textTransform: "uppercase",
                marginBottom: 6,
              }}
            >
              Detail Level
            </div>
            <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
              {DETAILS.map((d) => (
                <button
                  key={d.id}
                  onClick={() => setDetail(d.id)}
                  aria-pressed={detail === d.id}
                  style={{
                    flex: 1,
                    minWidth: "100px",
                    background:
                      detail === d.id
                        ? `linear-gradient(135deg, ${T.tealGlass}, rgba(34,164,193,0.04))`
                        : "transparent",
                    border: `1px solid ${detail === d.id ? T.tealBorder : T.border}`,
                    borderRadius: 9,
                    padding: "8px 8px",
                    textAlign: "center",
                    cursor: "pointer",
                    transition: "all 0.2s ease",
                  }}
                >
                  <div
                    style={{
                      fontSize: 12,
                      fontWeight: 600,
                      color: detail === d.id ? T.text : T.muted,
                    }}
                  >
                    {d.label}
                  </div>
                  <div style={{ fontSize: 9, color: T.dim, marginTop: 1 }}>
                    {d.desc}
                  </div>
                </button>
              ))}
            </div>
          </div>
        </Glass>

        {mode === "style-transfer" && (
          <SubjectInput value={styleSubject} onChange={setStyleSubject} />
        )}
        {mode === "variation" && (
          <VariationControls
            config={variationConfig}
            onChange={setVariationConfig}
          />
        )}

        {/* Upload Zone */}
        <Glass
          glow={dragOver}
          style={{
            padding: images.length > 0 ? 14 : 32,
            minHeight: images.length > 0 ? "auto" : 180,
            marginBottom: 16,
            display: "flex",
            flexDirection: "column",
            alignItems: images.length > 0 ? "stretch" : "center",
            justifyContent: images.length > 0 ? "flex-start" : "center",
            transition: "all 0.3s ease",
            animation: dragOver ? "vai-pulseGlow 1.5s ease infinite" : "none",
          }}
        >
          <input
            ref={fileRef}
            type="file"
            accept="image/*"
            multiple
            aria-label="Upload images"
            style={{ display: "none" }}
            onChange={(e) => {
              handleFiles(e.target.files);
              e.target.value = "";
            }}
          />

          {images.length === 0 ? (
            <div
              onClick={() => fileRef.current?.click()}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  fileRef.current?.click();
                }
              }}
              onDragOver={(e) => {
                e.preventDefault();
                setDragOver(true);
              }}
              onDragLeave={() => setDragOver(false)}
              onDrop={handleDrop}
              role="button"
              tabIndex={0}
              aria-label="Upload images by clicking or dropping files"
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: 10,
                width: "100%",
                cursor: "pointer",
              }}
            >
              <div
                style={{
                  width: 48,
                  height: 48,
                  borderRadius: 14,
                  background: `linear-gradient(135deg, ${T.tealGlass}, rgba(34,164,193,0.08))`,
                  border: `1px solid ${T.tealBorder}`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: T.teal,
                }}
              >
                <Icons.Upload />
              </div>
              <div style={{ textAlign: "center" }}>
                <div
                  style={{
                    fontSize: 14,
                    fontWeight: 600,
                    color: T.textSoft,
                  }}
                >
                  Drop images or tap to upload
                </div>
                <div style={{ fontSize: 11, color: T.dim, marginTop: 2 }}>
                  PNG, JPG, WebP &middot; Up to 20MB
                </div>
              </div>
            </div>
          ) : (
            <div>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  marginBottom: 10,
                }}
              >
                <span
                  style={{
                    fontFamily: "'Bebas Neue', sans-serif",
                    fontSize: 13,
                    letterSpacing: 1.5,
                    color: T.muted,
                  }}
                >
                  UPLOADED ({images.length})
                </span>
                <div style={{ display: "flex", gap: 6 }}>
                  <button
                    onClick={() => {
                      setImages([]);
                      setResult(null);
                    }}
                    style={{
                      background: "rgba(239,68,68,0.06)",
                      border: "1px solid rgba(239,68,68,0.1)",
                      borderRadius: 7,
                      padding: "3px 10px",
                      fontSize: 10,
                      color: "rgba(239,68,68,0.7)",
                      cursor: "pointer",
                      fontFamily: "'Reddit Sans', sans-serif",
                    }}
                  >
                    Clear
                  </button>
                  <button
                    onClick={() => fileRef.current?.click()}
                    style={{
                      background: T.glassHover,
                      border: `1px solid ${T.border}`,
                      borderRadius: 7,
                      padding: "3px 10px",
                      fontSize: 10,
                      color: T.muted,
                      cursor: "pointer",
                      fontFamily: "'Reddit Sans', sans-serif",
                    }}
                  >
                    + Add
                  </button>
                </div>
              </div>
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(auto-fill, minmax(80px, 1fr))",
                  gap: 6,
                }}
                onDragOver={(e) => {
                  e.preventDefault();
                  setDragOver(true);
                }}
                onDragLeave={() => setDragOver(false)}
                onDrop={handleDrop}
              >
                {images.map((img) => (
                  <div
                    key={img.id}
                    style={{
                      position: "relative",
                      borderRadius: 8,
                      overflow: "hidden",
                      border: `1px solid ${T.border}`,
                      aspectRatio: "1",
                    }}
                  >
                    <img
                      src={img.src}
                      alt={img.name}
                      style={{
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                      }}
                    />
                    <button
                      onClick={() => removeImage(img.id)}
                      aria-label={`Remove ${img.name}`}
                      style={{
                        position: "absolute",
                        top: 3,
                        right: 3,
                        width: 20,
                        height: 20,
                        borderRadius: 5,
                        background: "rgba(0,0,0,0.65)",
                        border: `1px solid ${T.border}`,
                        color: T.muted,
                        cursor: "pointer",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                      }}
                    >
                      <Icons.X />
                    </button>
                    <div
                      style={{
                        position: "absolute",
                        bottom: 0,
                        left: 0,
                        right: 0,
                        padding: "10px 5px 3px",
                        background:
                          "linear-gradient(transparent, rgba(0,0,0,0.75))",
                        fontSize: 8,
                        color: T.dim,
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                        whiteSpace: "nowrap",
                        fontFamily: "'JetBrains Mono', monospace",
                      }}
                    >
                      {img.name}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </Glass>

        {/* Analyze Button */}
        <button
          onClick={analyze}
          disabled={!canAnalyze}
          aria-busy={analyzing}
          style={{
            width: "100%",
            padding: "13px 20px",
            borderRadius: 11,
            border: "none",
            background: !canAnalyze
              ? T.panel
              : analyzing
                ? T.tealGlass
                : `linear-gradient(135deg, ${T.teal} 0%, ${T.beam} 50%, rgba(34,164,193,0.85) 100%)`,
            color: !canAnalyze ? T.dim : T.text,
            fontSize: 13,
            fontWeight: 600,
            fontFamily: "'Reddit Sans', sans-serif",
            letterSpacing: 0.3,
            cursor: !canAnalyze ? "not-allowed" : "pointer",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: 8,
            transition: "all 0.3s ease",
            boxShadow:
              canAnalyze && !analyzing
                ? `0 4px 20px ${T.tealGlow}, 0 1px 0 inset rgba(255,255,255,0.1)`
                : "none",
            marginBottom: 20,
          }}
        >
          {analyzing ? (
            <>
              <Icons.Loader /> Deconstructing Visual DNA...
            </>
          ) : (
            <>
              <Icons.Sparkle /> {analyzeLabel}
            </>
          )}
        </button>

        {analyzing && <AnalysisProgress stage={analyzing} />}

        <HistoryPanel
          history={history}
          onSelect={loadFromHistory}
          onClear={() => setHistory([])}
          onRemove={(id) => setHistory((h) => h.filter((x) => x.id !== id))}
        />

        {/* Results */}
        {result && (
          <div
            ref={resultsRef}
            style={{
              display: "flex",
              flexDirection: "column",
              gap: 14,
              animation: "vai-fadeIn 0.4s ease",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                margin: "4px 0",
              }}
            >
              <span
                style={{
                  flex: 1,
                  height: 1,
                  background: `linear-gradient(90deg, transparent, ${T.tealBorder}, transparent)`,
                }}
              />
              <span
                style={{
                  fontSize: 9,
                  letterSpacing: 2.5,
                  color: T.teal,
                  fontFamily: "'Bebas Neue', sans-serif",
                  padding: "3px 12px",
                  borderRadius: 20,
                  background: T.tealGlass,
                  border: `1px solid ${T.tealBorder}`,
                }}
              >
                RESULTS
              </span>
              <span
                style={{
                  flex: 1,
                  height: 1,
                  background: `linear-gradient(90deg, transparent, ${T.tealBorder}, transparent)`,
                }}
              />
            </div>

            {result.error ? (
              <Glass style={{ padding: 20 }}>
                <div
                  role="alert"
                  style={{ color: T.error, fontSize: 13, lineHeight: 1.6 }}
                >
                  {result.message}
                </div>
                <div style={{ fontSize: 11, color: T.dim, marginTop: 8 }}>
                  An issue occurred. If the error persists, try a smaller image
                  or fewer images.
                </div>
              </Glass>
            ) : (
              <>
                <div style={{ display: "flex", justifyContent: "flex-end" }}>
                  <button
                    onClick={exportPrompt}
                    style={{
                      background: T.glassHover,
                      border: `1px solid ${T.border}`,
                      borderRadius: 7,
                      padding: "5px 12px",
                      fontSize: 11,
                      color: T.muted,
                      cursor: "pointer",
                      display: "flex",
                      alignItems: "center",
                      gap: 5,
                      fontFamily: "'Reddit Sans', sans-serif",
                      transition: "all 0.2s ease",
                    }}
                  >
                    <Icons.Download /> Export .txt
                  </button>
                </div>

                {result.prompt && (
                  <Glass
                    glow
                    style={{
                      padding: 16,
                      position: "relative",
                      overflow: "hidden",
                    }}
                  >
                    <div
                      style={{
                        position: "absolute",
                        top: 0,
                        left: 0,
                        right: 0,
                        height: 1,
                        background: `linear-gradient(90deg, transparent 0%, ${T.teal} 50%, transparent 100%)`,
                        opacity: 0.3,
                      }}
                    />
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        marginBottom: 10,
                      }}
                    >
                      <span
                        style={{
                          fontFamily: "'Bebas Neue', sans-serif",
                          fontSize: 15,
                          letterSpacing: 1.5,
                          color: T.teal,
                        }}
                      >
                        {mode === "negative"
                          ? "NEGATIVE PROMPT"
                          : "GENERATED PROMPT"}
                      </span>
                      <CopyBtn text={result.prompt} />
                    </div>
                    <div
                      style={{
                        background:
                          "linear-gradient(135deg, rgba(9,10,15,0.6), rgba(14,16,23,0.8))",
                        borderRadius: 9,
                        padding: 14,
                        border: `1px solid ${T.borderSubtle}`,
                        fontSize: 12,
                        lineHeight: 1.75,
                        color: T.textSoft,
                        fontFamily: "'JetBrains Mono', monospace",
                        whiteSpace: "pre-wrap",
                        maxHeight: 400,
                        overflowY: "auto",
                        wordBreak: "break-word",
                      }}
                    >
                      {result.prompt}
                    </div>
                    {platform !== "universal" && (
                      <div
                        style={{
                          marginTop: 6,
                          fontSize: 9,
                          color: T.dim,
                          fontFamily: "'JetBrains Mono', monospace",
                        }}
                      >
                        Optimized for{" "}
                        {PLATFORMS.find((p) => p.id === platform)?.label}
                      </div>
                    )}
                  </Glass>
                )}

                {result.variants?.length > 0 && (
                  <Glass accent style={{ padding: 16 }}>
                    <Collapsible title="PROMPT VARIANTS">
                      <div
                        style={{
                          display: "flex",
                          flexDirection: "column",
                          gap: 10,
                        }}
                      >
                        {result.variants.map((v, i) => (
                          <div key={i} style={{ position: "relative" }}>
                            <div
                              style={{
                                display: "flex",
                                alignItems: "center",
                                justifyContent: "space-between",
                                marginBottom: 6,
                              }}
                            >
                              <span
                                style={{
                                  fontSize: 10,
                                  color: T.teal,
                                  fontFamily: "'JetBrains Mono', monospace",
                                  fontWeight: 600,
                                }}
                              >
                                VARIANT {i + 1}
                              </span>
                              <CopyBtn text={v} />
                            </div>
                            <div
                              style={{
                                background: "rgba(9,10,15,0.5)",
                                borderRadius: 8,
                                padding: 12,
                                border: `1px solid ${T.borderSubtle}`,
                                fontSize: 11,
                                lineHeight: 1.65,
                                color: "rgba(241,245,249,0.75)",
                                fontFamily: "'JetBrains Mono', monospace",
                                whiteSpace: "pre-wrap",
                                wordBreak: "break-word",
                              }}
                            >
                              {v}
                            </div>
                          </div>
                        ))}
                      </div>
                    </Collapsible>
                  </Glass>
                )}

                {result.technical && (
                  <Glass accent style={{ padding: 16 }}>
                    <Collapsible title="TECHNICAL BREAKDOWN">
                      <div
                        style={{
                          display: "flex",
                          justifyContent: "flex-end",
                          marginBottom: 8,
                        }}
                      >
                        <CopyBtn text={result.technical} />
                      </div>
                      <div
                        style={{
                          fontSize: 12,
                          lineHeight: 1.7,
                          color: "rgba(241,245,249,0.7)",
                          whiteSpace: "pre-wrap",
                          wordBreak: "break-word",
                        }}
                      >
                        {result.technical}
                      </div>
                    </Collapsible>
                  </Glass>
                )}

                {result.tags?.length > 0 && (
                  <Glass style={{ padding: 16 }}>
                    <Collapsible title="STYLE TAGS">
                      <div
                        style={{
                          display: "flex",
                          justifyContent: "flex-end",
                          marginBottom: 8,
                        }}
                      >
                        <CopyBtn text={result.tags.join(", ")} />
                      </div>
                      <div
                        style={{ display: "flex", flexWrap: "wrap", gap: 5 }}
                      >
                        {result.tags.map((tag, i) => (
                          <span
                            key={i}
                            style={{
                              background: `linear-gradient(135deg, ${T.tealGlass}, rgba(51,65,85,0.08))`,
                              border: "1px solid rgba(0,206,209,0.12)",
                              borderRadius: 6,
                              padding: "3px 9px",
                              fontSize: 10,
                              color: T.cyan,
                              fontFamily: "'JetBrains Mono', monospace",
                            }}
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    </Collapsible>
                  </Glass>
                )}

                {result.negativePrompt && mode !== "negative" && (
                  <Glass style={{ padding: 16 }}>
                    <Collapsible
                      title="NEGATIVE PROMPT"
                      defaultOpen={false}
                    >
                      <div
                        style={{
                          display: "flex",
                          justifyContent: "flex-end",
                          marginBottom: 8,
                        }}
                      >
                        <CopyBtn text={result.negativePrompt} />
                      </div>
                      <div
                        style={{
                          background: "rgba(239,68,68,0.04)",
                          borderRadius: 9,
                          padding: 12,
                          border: "1px solid rgba(239,68,68,0.08)",
                          fontSize: 11,
                          lineHeight: 1.6,
                          color: "rgba(241,245,249,0.6)",
                          fontFamily: "'JetBrains Mono', monospace",
                          whiteSpace: "pre-wrap",
                          wordBreak: "break-word",
                        }}
                      >
                        {result.negativePrompt}
                      </div>
                    </Collapsible>
                  </Glass>
                )}
              </>
            )}
          </div>
        )}
      </main>

      {/* Footer — VASEY/AI Universal Branded Footer */}
      <footer
        style={{
          position: "relative",
          zIndex: 5,
          maxWidth: 900,
          margin: "0 auto",
          marginTop: 56,
          paddingTop: 32,
          paddingBottom: "calc(24px + env(safe-area-inset-bottom, 0px))",
          paddingLeft: "calc(16px + env(safe-area-inset-left, 0px))",
          paddingRight: "calc(16px + env(safe-area-inset-right, 0px))",
          borderTop: `1px solid ${T.borderSubtle}`,
          textAlign: "center",
          animation: "vai-fadeIn 0.8s ease 0.8s both",
        }}
      >
        {/* Divider accent */}
        <div
          style={{
            width: 48,
            height: 1,
            background: `linear-gradient(90deg, transparent, ${T.tealBorder}, transparent)`,
            margin: "0 auto 28px",
          }}
        />

        {/* Brand logos row */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: 20,
            marginBottom: 20,
          }}
        >
          {/* Vasey Multimedia — VM Monogram */}
          <a
            href="https://vaseymultimedia.com"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Vasey Multimedia"
            style={{ opacity: 0.45, display: "inline-flex", alignItems: "center", transition: "opacity 0.3s ease" }}
            onMouseEnter={(e) => { e.currentTarget.style.opacity = 0.75; }}
            onMouseLeave={(e) => { e.currentTarget.style.opacity = 0.45; }}
          >
            <svg width="36" height="31" viewBox="0 0 688 592" xmlns="http://www.w3.org/2000/svg">
              <g transform="translate(0,592) scale(0.1,-0.1)" fill="currentColor" style={{ color: T.muted }}>
                <path d="M20 3827 l0 -2073 251 -265 c138 -145 281 -299 317 -341 37 -42 70 -76 74 -75 3 1 8 851 10 1889 2 1038 8 1891 12 1895 5 4 11 2 13 -5 3 -7 51 -70 106 -139 144 -178 444 -556 611 -767 77 -98 193 -245 257 -325 64 -80 223 -281 353 -446 130 -165 301 -381 380 -480 78 -99 205 -261 282 -359 76 -99 176 -227 222 -285 46 -58 104 -133 130 -166 323 -418 405 -517 415 -499 13 24 111 152 237 309 83 104 193 244 345 438 22 29 76 97 120 153 44 56 116 148 160 205 44 57 213 270 375 474 162 203 307 386 322 405 15 19 89 112 165 207 76 94 174 218 217 275 44 57 202 258 350 447 317 403 353 448 409 521 l42 55 3 -1903 c1 -1047 6 -1902 10 -1900 4 2 50 50 102 108 52 58 184 197 294 310 110 113 211 221 225 241 l26 35 0 225 c0 123 -1 1053 -2 2067 l-3 1842 -323 0 c-309 0 -323 -1 -332 -19 -6 -11 -57 -79 -115 -151 -126 -158 -178 -226 -377 -486 -83 -109 -191 -249 -240 -311 -48 -61 -166 -212 -262 -335 -197 -251 -337 -430 -522 -663 -70 -88 -146 -186 -170 -217 -120 -155 -371 -476 -528 -673 -96 -121 -198 -249 -226 -285 -28 -36 -111 -140 -184 -232 l-133 -166 -27 31 c-15 18 -49 61 -77 97 -27 36 -103 133 -169 216 -66 82 -164 206 -217 275 -53 68 -170 216 -258 329 -89 113 -276 354 -417 535 -141 182 -289 371 -328 420 -39 50 -128 162 -196 250 -69 88 -181 232 -250 319 -68 87 -221 283 -339 435 -119 152 -271 345 -338 429 -67 84 -129 164 -138 177 l-16 25 -324 0 -324 0 0 -2073z M1209 5883 c5 -10 66 -90 136 -178 69 -88 176 -225 238 -305 61 -80 146 -188 187 -241 41 -52 106 -136 145 -185 38 -49 121 -155 185 -235 63 -80 141 -179 172 -220 62 -79 308 -394 532 -679 213 -272 298 -381 471 -603 88 -114 162 -206 165 -206 3 0 21 21 41 47 19 26 109 141 200 256 90 115 247 315 348 445 236 302 465 594 547 696 102 128 375 474 563 716 96 123 216 276 266 339 50 63 136 171 190 240 l98 125 -374 3 c-292 2 -375 0 -380 -10 -4 -7 -102 -132 -218 -278 -116 -146 -223 -281 -238 -301 -98 -128 -269 -345 -333 -423 -41 -50 -93 -116 -115 -146 -22 -30 -78 -102 -125 -160 -78 -96 -186 -232 -388 -490 -41 -52 -79 -95 -83 -95 -5 0 -46 48 -91 106 -101 129 -455 578 -750 949 -509 643 -621 786 -642 817 l-21 33 -368 0 c-347 0 -367 -1 -358 -17z M1130 2171 l0 -1484 163 -166 c156 -159 343 -353 437 -453 25 -27 48 -48 53 -48 4 0 7 637 7 1415 l0 1415 -33 37 c-19 21 -151 184 -295 363 -144 179 -277 343 -296 365 l-35 40 -1 -1484z M5633 3532 c-50 -64 -193 -245 -317 -401 l-226 -284 0 -1413 c0 -887 4 -1414 10 -1414 5 0 13 6 17 14 10 18 110 125 267 286 66 69 175 181 241 250 l120 125 -3 1478 c-1 812 -5 1477 -10 1476 -4 0 -48 -53 -99 -117z" />
              </g>
            </svg>
          </a>

          {/* Separator */}
          <div style={{ width: 1, height: 24, background: T.border }} />

          {/* VASEY/AI — V/AI Monogram */}
          <a
            href="https://vasey.ai"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="VASEY/AI"
            style={{ opacity: 0.45, display: "inline-flex", alignItems: "center", transition: "opacity 0.3s ease" }}
            onMouseEnter={(e) => { e.currentTarget.style.opacity = 0.75; }}
            onMouseLeave={(e) => { e.currentTarget.style.opacity = 0.45; }}
          >
            <svg width="34" height="34" viewBox="0 0 1080 1080" xmlns="http://www.w3.org/2000/svg">
              <g transform="translate(0,1080) scale(0.1,-0.1)">
                <path d="M5797 7988 c-15 -12 -38 -53 -162 -283 -26 -49 -75 -139 -108 -200 -58 -107 -233 -435 -334 -625 -84 -157 -278 -521 -311 -580 -16 -30 -127 -239 -247 -465 -119 -225 -233 -439 -252 -475 -20 -36 -76 -141 -125 -235 -50 -93 -105 -197 -123 -230 -18 -33 -73 -136 -123 -230 -49 -93 -99 -187 -111 -209 -12 -21 -62 -114 -111 -206 -49 -92 -97 -183 -108 -201 -10 -19 -42 -78 -72 -131 -29 -54 -59 -98 -66 -98 -17 0 -34 32 -34 61 0 21 63 146 190 379 196 358 240 441 240 454 0 13 -482 978 -500 1001 -5 6 -74 141 -155 300 -81 160 -195 382 -253 495 -58 113 -134 262 -168 332 -35 70 -71 131 -81 136 -20 11 -983 3 -983 -7 0 -3 31 -62 68 -131 37 -69 103 -192 146 -275 44 -82 129 -244 191 -360 62 -115 143 -268 180 -340 37 -71 103 -195 145 -275 43 -80 105 -199 140 -265 35 -66 82 -156 105 -200 24 -44 118 -224 210 -400 92 -176 202 -385 245 -465 42 -80 119 -226 171 -325 51 -99 133 -256 181 -350 49 -93 147 -286 218 -427 115 -227 134 -258 154 -258 20 0 39 29 136 208 62 114 166 304 230 422 175 321 310 571 380 705 35 66 148 280 253 475 104 195 208 391 232 435 23 44 102 193 175 330 73 138 182 342 243 455 61 113 122 225 135 250 67 125 125 232 162 300 22 41 70 134 107 205 36 72 181 346 323 610 141 264 280 524 309 578 29 54 50 105 47 113 -5 12 -73 14 -439 14 -331 0 -437 -3 -450 -12z M8839 6962 c-42 -20 -114 -55 -160 -76 -152 -71 -473 -226 -529 -256 l-55 -29 -9 -318 c-5 -180 -5 -886 0 -1618 l9 -1300 420 0 420 0 0 1814 c0 1201 -3 1815 -10 1817 -5 1 -44 -14 -86 -34z M5983 6518 c-5 -7 -26 -44 -45 -83 -20 -38 -106 -200 -191 -359 -86 -158 -159 -297 -162 -307 -6 -17 98 -224 285 -574 15 -27 57 -109 94 -182 36 -72 74 -141 84 -152 17 -19 29 -20 424 -22 224 -2 410 0 414 4 3 3 -9 34 -29 69 -41 74 -313 594 -447 853 -265 515 -399 765 -410 765 -4 0 -12 -6 -17 -12z M5066 4761 c-19 -7 -101 -146 -281 -474 -76 -139 -105 -201 -97 -209 7 -7 487 -10 1571 -10 859 -1 1564 2 1567 5 4 3 -16 45 -44 94 -27 48 -74 135 -105 193 -130 249 -200 376 -215 393 -14 16 -83 17 -1196 16 -650 0 -1189 -4 -1200 -8z M6450 3977 c0 -8 15 -43 33 -78 19 -35 78 -149 132 -254 54 -104 101 -194 105 -200 9 -12 97 -182 323 -620 206 -401 225 -435 251 -444 12 -4 227 -5 479 -3 l457 4 -86 167 c-124 237 -179 341 -244 461 -31 58 -85 159 -120 225 -34 66 -79 152 -100 190 -21 39 -75 142 -120 230 -46 87 -104 195 -130 240 l-46 80 -49 6 c-28 3 -238 7 -467 8 -355 2 -418 0 -418 -12z" fill="currentColor" style={{ color: T.muted }} />
              </g>
            </svg>
          </a>
        </div>

        {/* Suite tag */}
        <div
          style={{
            fontFamily: "'Reddit Sans', sans-serif",
            fontSize: 12,
            fontWeight: 500,
            letterSpacing: "0.25em",
            textTransform: "uppercase",
            color: T.dim,
            marginBottom: 8,
          }}
        >
          A VASEY/AI Production
        </div>

        {/* App tag */}
        <div
          style={{
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: 11,
            color: T.dim,
            opacity: 0.7,
            marginBottom: 16,
          }}
        >
          REGENESYS v1.2 &middot; Visual Prompt Reverse-Engineering &amp; Generation
        </div>

        {/* Copyright */}
        <div
          style={{
            fontFamily: "'Reddit Sans', sans-serif",
            fontSize: 11,
            color: T.dim,
            opacity: 0.5,
            lineHeight: 1.6,
            paddingBottom: 8,
          }}
        >
          &copy; 2026{" "}
          <a
            href="https://vaseymultimedia.com"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: T.slate, textDecoration: "none" }}
          >
            VASEY Multimedia
          </a>
          . All rights reserved.
          <br />
          Designed &amp; engineered by{" "}
          <a
            href="https://vasey.ai"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: T.slate, textDecoration: "none" }}
          >
            VASEY/AI
          </a>
        </div>
      </footer>
    </div>
  );
}
